### ISSUE TITLE
Apk from Github Action not installable

### ISSUE THREAD

**Issue by skdubg** [OlauncherCF/OlauncherCF#226]
- [x] I have searched existing issues for this bug.

#### Bug description

version 1.4.0 can't be installed

#### Steps to reproduce

1. try to install 1.4.0 apk

#### Environment information

- Olauncher CF version: 1.4.0
- Device name: irrelevant
- Android version: irrelevant
- Other information: irrelevant

#### Additional context (that might help us to solve your problem)

- the following messages apears: "package is not valid"

**Comment by jooooscha** [comment]
Ok, the following information are directly relevant:

- Android Version
- Do you use Lineage OS?
- Did you have the fdroid version installed or did you delete that first?
- Did you have any self compiled versions installed?

Device name might be not directly relevat, but could help if this error turns out to happen only to you.

It would also be good to mention that you tried to install the apk from the github release. This might me clear now, but not in a few days when the fdroid version will be available.

**Comment by jooooscha** [comment]
for reference #196

**Comment by skdubg** [comment]
hi,


-     Android Version: _12_
-     Do you use Lineage OS?: _no_
-     Did you have the fdroid version installed or did you delete that first?: _fdroid version is installed_
-     Did you have any self compiled versions installed? _no_

**Comment by skdubg** [comment]
Fdroid release update is working 👍

**Comment by jooooscha** [comment]
Also related #232

Closing, please use #196 for further discussion
