### ISSUE TITLE
App Rename like in Сlassic Olauncher

### ISSUE THREAD

**Issue by AntonDzutstsati** [OlauncherCF/OlauncherCF#289]
### Checklist

- [X] I have searched for existing issues about this feature.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Motivation

For the sake of convenience.

### Feature description

Right now if you want to change app's name, you have to do it separately on Home Screen and in App Drawer. In Classic Olauncher you only have to change name in App Drawer and it will remain the same after adding on Home Screen.

### Alternatives

There is no alternatives.

**Comment by jooooscha** [comment]
Yes, I should take a look at it, although, it will require quite a bit of refactoring. I will see what i can do.

**Comment by D-ominik** [comment]
In my opinion, it's a great feature to have the option to name apps differently on the home screen than in the app drawer.

I only have a very small selection of apps on the home screen. I don't need to differentiate between the various types of apps here because only my favorites are shown. That's why my mail program on the home screen is simply called "Mail" instead of  "K9 Mail". However, it is necessary to differentiate between Gmail and K9 Mail in the app drawer, for example.

Only a very small number of apps can be placed on the home screen and you certainly don't change them every day. The effort required to rename them twice therefore is limited.

**Comment by jooooscha** [comment]
I agree, the amount of changes this would require vs. the very limited value this brings is not worth it
